apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pebble-issuer
spec:
  acme:
    skipTLSVerify: true
    email: your@mail.com
    server: https://pebble.default:14000/dir
    privateKeySecretRef:
      name: pk-pebble-issuer
    solvers:
      - selector:
        http01:
          ingress:
            class: nginx