apiVersion: v1
kind: Service
metadata:
  name: pebble
spec:
  type: ClusterIP
  ports:
    - port: 14000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: pebble
---
apiVersion: v1
kind: Service
metadata:
  name: pebble-mgmt
spec:
  type: ClusterIP
  ports:
    - port: 15000
      targetPort: http-mgmt
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: pebble
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pebble
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pebble
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pebble
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: pebble
          items:
          - key: pebble-config.json
            path: pebble-config.json
      containers:
      - image: ghcr.io/letsencrypt/pebble:latest
        imagePullPolicy: Always
        name: pebble
        ports:
        - name: http
          containerPort: 14000
          protocol: TCP
        - name: http-mgmt
          containerPort: 15000
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /test/config/pebble-config.json
          subPath: pebble-config.json
          readOnly: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pebble
data:
  pebble-config.json: |
    {
      "pebble": {
        "listenAddress": "0.0.0.0:14000",
        "managementListenAddress": "0.0.0.0:15000",
        "certificate": "test/certs/localhost/cert.pem",
        "privateKey": "test/certs/localhost/key.pem",
        "httpPort": 80,
        "tlsPort": 443,
        "ocspResponderURL": "",
        "externalAccountBindingRequired": false
      }
    }